# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bfec765a84a0ddf2d22340fb2e82bedca7b86582d01ab08ec0240ca965916ad6c400b0c75cd14c9f88f70e1347e1886b75158dfcc873a4a218cb0f4e629a2d8a

test:
  secret_key_base: 4bc6938fc1ee3a6ef06012071a136afa48a493ccf2c8c5af21b3b350048376beaf6d62724000b25eb0165cc15ce278426e314e5ed884a9fe244fa8ee5b6cadb8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
